### Sign up user with email and password
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

### Sign in user with email and password
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

### Get the current user
GET http://localhost:3000/auth/whoami

### sign out logged in user
POST http://localhost:3000/auth/signout



### Get user by ID
GET http://localhost:3000/auth/9

### Get all users with a particular email address.
GET http://localhost:3000/auth?email=asdf@gmail.com

### Update user by ID
PATCH http://localhost:3000/auth/8
Content-Type: application/json

{
    "password": "aaa"
}

### Delete user by ID
DELETE http://localhost:3000/auth/7


### Session set a color
GET http://localhost:3000/auth/colors/red

### Get the color
GET http://localhost:3000/auth/colors